#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);

##################################################
sub usage(){
print qq*
$0 - photoalbum cleanup

Usage:
  $0 <options> <infile>

Options:
    -h,--help    -- display help screen
    -f,--force   -- don\'t ask before remothing of files
    -d,--dryrun  -- only list files to be removed

Report bugs to <slazav\@altlinux.org>
*;
exit(1);
}


##################################################
### get options 

my %opts;
GetOptions(
  "h|help"     => \$opts{help},
  "f|force"    => \$opts{force},
  "d|dryrun"   => \$opts{dryrun},
) or usage();

usage() if $opts{help};

die "error: --force and --dryrun options can't be used together\n"
  if $opts{force} && $opts{dryrun};
die "error: single filename expected\n" if @ARGV!=1;
$opts{infile} = shift;
die "error: can't find file: $opts{infile}\n" unless -f $opts{infile};

