#!/bin/sh -eu

# normalize photo names, autorotate

count=0
# convert names to lowercase
echo "1. convert names"
for i in $(find . -maxdepth 1 -name '*.JPG' -or -name '*.jpg'); do
  i="${i#./}"
  chmod 644 "$i"
  count="$(($count+1))"

  n="$(echo "$i" | tr 'A-Z' 'a-z')"
  n="${n#img_}"
  n="${n#dsc}"

  [ "$n" != "$i" ] || continue

  if [ -f "$n" ]; then
    echo "Warning: converting $i to lowercase: $n exists!"
    for l in a b c d e f g h i j k l m\
             n o p q r s t u v w x y z; do
      nn="${n%.jpg}$l.jpg"
      if ! [ -f "$nn" ]; then
        n="$nn"
        echo "Renaming $i to $n"
        break
      fi
    done
  fi
  [ ! -f "$n" ] || { printf "Can't find uniq name for $i!\n"; exit 1; }

  mv "$i" "$n"
  echo "Renaming $i to $n..."
done

[ "$count" != 0 ] || { printf "No jpeg files found!\n"; exit 1; }
echo "$count jpeg files found"

# rescale images
echo "2. rescale to 2048x1536px"
ph_resize -v -i -S 1536:1536:20000 *.jpg

# autorotate photos
echo "3. autorotate"
exifautotran *.jpg
exiv2 -M 'del Exif.Image.Orientation' *.jpg
