#!/bin/sh -eu

. shell-error

[ "$#" = 1 ] ||
{
  cat <<EOF

addphoto_ini - create template for a photoalbum

Usage: addphoto_ini <photo dir>

NOTE: all jpg images if photo dir will be rescaled!

Report bugs to <slazav@altlinux.org>

EOF
exit
}


dir="$1"
file="$dir.m4p"

[ ! -f "$file" ] || mv -f "$file" "$file.bak"

cat > $file <<EOF
<html>
<head>
  <title>${title:-}</title>
</head>
<body>
  <h2 align="center">${title:-}</h2>

EOF

ww=0
odate=


ph_towww $dir/[^_]*.jpg
for i in $dir/[^_]*.jpg; do

  [ -f "$i" ] || fatal "no *.jpg files found!"

  tfile="${i%/*}/_${i##*/}"

  [ ! "$i" -nt "$tfile" ] ||
    ph_resize "$i" "$tfile" 200 100 600

  s="$(ph_size "$tfile")"
  w="${s%% *}"

  date="$(exiv2 -Pkv $i 2>/dev/null |\
          sed -n 's/Exif.Photo.DateTimeOriginal[[:space:]]*\([0-9:]\+\).*/\1/p' | tr ':' '/')"

  if [ "$odate" != "$date" ]; then
    echo -e "\n<hr><h4>$date</h4>\n" >> "$file"
    ww=0
    odate="$date"
  fi

  ww="$(($ww+$w))"
  if [ "$(($ww>600))" = 1 ]; then
    echo "" >> "$file"
    ww="$w"
  fi
  echo "\photo ${i#$dir/}" >> "$file"
done

cat >> $file <<EOF
</body>
</html>
EOF

addphoto "$file" "${file%.m4p}.htm"