#!/usr/bin/perl

use strict;
use warnings;

my $k=14.2875; # convert pixel -> fig units;

#################################################################
sub usage(){
print qq*
$0 -- create fig with image for drawing marks

Usage: $0 <file>

You can add this to your gqviewrc:
external_8: "fig" "file=\%p; $0 \$file; xfig \${file\%.\*}.fig &"

Report bugs to <slazav\@altlinux.org>
*;
exit(1);
}

#################################################################
# same as in addphoto

## split path into full directory name + basename + last extension
## './some/path/file.e1.e2.ext' -> './some/path/' + 'file.e1.e2' + '.ext'
sub path_split($){
  $_[0]=~m&(.*\/)?((.*)(\..*)|(.*)())&;
  return (($1 or ''), ($3 or $5 or ''), ($4 or $6 or ''));
}

## get image size (identify from ImageMagick is needed).
sub image_size($){
  `identify "$_[0]" 2> /dev/null` =~/(\d+)x(\d+)/;
  return ($1 || 0, $2 || 0);
}

#################################################################

usage() if @ARGV!=1;
my $file=$ARGV[0];

my ($w, $h) = image_size($file);
$w=int($w*$k); $h=int($h*$k);

my ($d, $b, $e) = path_split($file);
my $fig="$d$b.fig";
exit(0) if -f $fig;

open OUT, "> $fig" or die "Can't open $fig: $!\n";
print OUT qq*#FIG 3.2  Produced by addphoto_mkfig
Landscape
Center
Metric
A4
100.00
Single
-2
1200 2
2 5 0 1 0 -1 500 -1 -1 0.000 0 0 -1 0 0 5
        0 $b$e
        0 0 $w 0 $w $h 0 $h 0 0
*;
