#!/bin/sh -fu

# Edit ImageDescription and UserComment (used for keywords)
# exif tags with Xdialog

FILE="$1"
[ -f "$FILE" ] || exit

TXT1="$(exiv2 $FILE -PEkt | sed -n 's/^Exif.Image.ImageDescription *//p')"
TXT2="$(exiv2 $FILE -PEkt | sed -n 's/^Exif.Photo.UserComment *//p')"

# it's better to use \n separator here, but $() cuts trailing newline
# and this should be checked specially
S="|"
TXT="$(Xdialog --stdout --title "ImageDescription" --separator "$S"\
       --2inputsbox "" 12 80 Description "$TXT1" Keywords "$TXT2" )" && {
  echo "<<$TXT>>"
  exiv2 -M"set Exif.Image.ImageDescription ${TXT%$S*}" "$FILE"
  exiv2 -M"set Exif.Photo.UserComment ${TXT#*$S}" "$FILE"
}
