#!/bin/sh -efu

# Create fig-file for a given image

# Add this to you gqviewrc:
# external_8: "fig" "file=%p; addphoto_mkfig $file; xfig ${file%.*}.fig &"

if [ "$#" != 1 ]; then
  cat <<EOF

addphoto_mkfig -- create fig with image for drawing marks

usage: addphoto_mkfig <file>

EOF
exit
fi

file="$1"
s="$(ph_size $file)"
w="${s%% *}"
h="${s##* }"

k=14.2875

w="$(printf "$w*$k\n" | bc -l)";  w="${w%.*}"
h="$(printf "$h*$k\n" | bc -l)";  h="${h%.*}"

fig="${file%.*}.fig"

[ ! -f "$fig" ] || exit

cat > "$fig" << EOF
#FIG 3.2  Produced by addphoto_mkfig
Landscape
Center
Metric
A4
100.00
Single
-2
1200 2
2 5 0 1 0 -1 500 -1 -1 0.000 0 0 -1 0 0 5
        0 ${file##*/}
        0 0 $w 0 $w $h 0 $h 0 0
EOF