#!/usr/bin/perl -w
use strict;

# Add geodata from OziExplorer plt file to exif

my $dfn="0x9003";
#my $dfn="0x0132";

die "useage: $0 <time shift> <plt track-file> <jpg files>\n" if ($#ARGV<1);

my $tshift    = shift @ARGV;
my $plt_track = shift @ARGV;

open T, "$plt_track" or die "can't open $plt_track\n";

my @data;

foreach(<T>){
  my @pt_data = split /,/;
  next unless ($#pt_data==5) || ($#pt_data==6);
  my $alt = $pt_data[3]*0.3048;
  my $t   = int($pt_data[4]*24*3600 - 2209161600 + 3600*$tshift);
  push @data, {lat => $pt_data[0], lon => $pt_data[1], alt => $alt,
               t => $t, start => $pt_data[2]};
}

foreach (@ARGV){
  print "\n$_";
  my $date = `exiv2 -pv $_ | grep -a -- '^$dfn'`;
  next unless ($date=~/^.*\s+(\d+):(\d+):(\d+)\s+(\d+:\d+:\d+)$/);
  $date = "$1-$2-$3 $4";
  my $t = `date -d '$date' +%s`;
  print " $date";
  my $args=
    "-M 'del Exif.GPSInfo.GPSLatitudeRef' " .
    "-M 'del Exif.GPSInfo.GPSLongitudeRef' " .
    "-M 'del Exif.GPSInfo.GPSLatitude' " .
    "-M 'del Exif.GPSInfo.GPSLongitude' " .
    "-M 'del Exif.GPSInfo.GPSAltitudeRef' " .
    "-M 'del Exif.GPSInfo.GPSAltitude' ";

  for (my $i=0; $i<$#data; $i++){
    my $t1 = $data[$i]->{t};
    my $t2 = $data[$i+1]->{t};

    if (($t1 <= $t) && ($t2 > $t) && ($data[$i+1]->{start}==0)){

      my $lat1 = $data[$i]->{lat};
      my $lat2 = $data[$i+1]->{lat};
      my $lon1 = $data[$i]->{lon};
      my $lon2 = $data[$i+1]->{lon};
      my $alt1 = $data[$i]->{alt};
      my $alt2 = $data[$i+1]->{alt};

      if ($alt1<-1000) {$alt1=$alt2;}
      if ($alt2<-1000) {$alt2=$alt1;}
      my $k = ($t-$t1)/($t2-$t1);
      my $lat = $lat1 + ($lat2-$lat1)*$k;
      my $lon = $lon1 + ($lat2-$lat1)*$k;
      my $alt = $alt1 + ($alt2-$alt1)*$k;

      print " $lat $lon $alt ";

      my $lat_r = $lat<0? 'S':'N'; $lat=abs($lat);
      my $lon_r = $lon<0? 'W':'E'; $lon=abs($lon);
      my $lat_d = int($lat); $lat-=$lat_d;
      my $lon_d = int($lon); $lon-=$lon_d;
      my $lat_m = int($lat*60);
      my $lon_m = int($lon*60);
      my $lat_s = int(($lat*60-$lat_m)*60*100);
      my $lon_s = int(($lon*60-$lon_m)*60*100);

      $alt=int($alt*100);

      $args=
        "-M 'set Exif.GPSInfo.GPSLatitudeRef  Ascii $lat_r' " .
        "-M 'set Exif.GPSInfo.GPSLongitudeRef Ascii $lon_r' " .
        "-M 'set Exif.GPSInfo.GPSLatitude  $lat_d/1 $lat_m/1 $lat_s/100' " .
        "-M 'set Exif.GPSInfo.GPSLongitude $lon_d/1 $lon_m/1 $lon_s/100' " .
        "-M 'set Exif.GPSInfo.GPSAltitudeRef Byte 0' " .
        "-M 'set Exif.GPSInfo.GPSAltitude    $alt/100' ";
      $i=$#data;
    }
  }
  `exiv2 $args $_`;
}
print "\n";
