#!/bin/bash -efu

[ "$#" -gt 0 ] || {
cat <<EOF
ph_canon_rename -- rename photo made by Canon to original names

Usage: ph_canon_rename <one or more jpeg images>

Report bugs to slazav@altlinux.org
EOF
exit 1
}

for i in $@; do
  [ -s "$i" ] || continue
  exiv2 -Pkt $i | while read k v; do
#    [ "$k" = Exif.Canon.ImageNumber ] || continue ## old
    [ "$k" = Exif.Canon.FileNumber ] || continue
    mv "$i" "${v#*-}.jpg"
  done
done
